### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by jaller94** [7Geese/eslint-config-7geese#8]
According to the `package.json` the project is licensed under MIT. Please confirm this by uploading a `LICENSE` file with the legal text of the MIT license.

**Comment by himynameisdave** [comment]
@jaller94 Will do!

In your opinion, is that the most appropriate licence for this project? We want people/companies to be able to use and modify it as they see fit.

**Comment by jaller94** [comment]
In that case the chosen license of MIT is a good choice.
The only restriction it has, is that it requires attribution of copyright holders.
